spring.application.name=EBM
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-lingering-lake-aqrs8hxr-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GArhU3Q8SzjC
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
